# Generated by Django 5.1.3 on 2024-11-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_objective_delete_commandlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='completed',
        ),
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='??? ?????'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????? ???????'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(verbose_name='??? ?????'),
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='?????')),
                ('result', models.TextField(verbose_name='???????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????? ???????')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.objective', verbose_name='?????')),
            ],
        ),
    ]
